name: midas_env
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - matplotlib
      - numpy
      - pandas
      - parsl
      - scikit-image
      - pillow
      - h5py
      - numba
      - zarr==2.18.3
      - numcodecs==0.15.1
      - hdf5plugin
      - dash
      - plotly
      - dash_bootstrap_components
      - diplib
      - scipy
      - fsspec
      - opencv-python
      - globus_compute_sdk
      - globus_sdk
      - tqdm
      - diskcache
      - multiprocess
