# environment.yaml

name: midas-env
channels:
  - conda-forge
dependencies:
  - python>=3.5
  - anaconda
  - pip
  - matplotlib
  - numpy
  - pandas
  - scikit-image
  - parsl
  - pillow
  - h5py
  - numba
  - zarr
  - hdf5plugin
  - dash
  - dash-bootstrap-components
  - plotly
  - diplib
  - scipy
  - fsspec
  - opencv-python
  - tqdm
  - diskcache
  - multiprocess
  - PyQt6
  - pyqtgraph
  - xcb-util-cursor