name: Mirror Repository

on:
  push:
    branches: [ master ]  # Change this to match your default branch name
  schedule:
    - cron: '0 */12 * * *'  # Backup sync every 12 hours

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get all history, branches and tags
          lfs: true       # Enable Git LFS
          
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
      - name: Mirror to organization repository
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Set up SSH config
          mkdir -p ~/.ssh
          echo "Host github.com" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          
          # Add and push to mirror
          git remote add organization git@github.com:AdvancedPhotonSource/MIDAS.git
          git push organization --mirror
          
      - name: Delete workflows in mirror repository
        run: |
          # Clone the mirror repository
          git clone git@github.com:AdvancedPhotonSource/MIDAS.git mirror-repo
          cd mirror-repo
          
          # Remove workflow files
          rm -rf .github/workflows
          
          # Commit and push the change
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Remove workflow files from mirror" || echo "No changes to commit"
          git push