name: Mirror Repository

on:
  push:
    branches: [ master ]  # Change this to match your default branch name (main, master, etc.)
  schedule:
    - cron: '0 */1 * * *'  # Backup sync every 12 hours

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get all history, branches and tags 
          
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
      - name: Push to organization repository
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          # Making sure we disable strict host key checking
          mkdir -p ~/.ssh
          echo "Host github.com" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          git remote add organization git@github.com/AdvancedPhotonSource/MIDAS.git
          git push organization --mirror